name: ESP32 OTA Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # (we'll fill in build / serve / mqtt publish steps next)
