name: Build and Deploy Firmware OTA

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo "${PWD}/bin" >> $GITHUB_PATH

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile firmware
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32s3 ./src

    - name: Start Python HTTP server in background
      run: |
        nohup python3 -m http.server 8000 --directory ./src/build/esp32.esp32.esp32s3/ > server.log 2>&1 &

    - name: Expose HTTP server via Serveo
      run: |
        sudo apt-get install -y openssh-client
        ssh -o StrictHostKeyChecking=no -R 80:localhost:8000 serveo.net &
        sleep 15

    - name: Extract Serveo URL
      id: get-url
      run: |
        URL=$(curl -s https://serveo.net/status | grep -Eo 'https?://[a-zA-Z0-9.-]+serveo.net' | head -n 1)
        echo "OTA_URL=$URL/firmware.bin" >> $GITHUB_ENV
        echo "Firmware will be served from: $URL/firmware.bin"

    - name: Rename binary to firmware.bin
      run: |
        cp ./src/build/esp32.esp32.esp32s3/src.ino.bin ./src/build/esp32.esp32.esp32s3/firmware.bin

    - name: Publish OTA URL to MQTT
      run: |
        pip install paho-mqtt
        python3 -c "
import paho.mqtt.publish as publish
publish.single(
    topic='esp32/ota',
    payload='${{ env.OTA_URL }}',
    hostname='test.mosquitto.org',
    port=1883
)
"
