name: OTA Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-serve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python HTTP range server
        run: |
          pip install rangehttpserver

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "${PWD}/bin" >> $GITHUB_PATH

      - name: Set up ESP32 core
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile sketch
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32s3:esp32s3_dev \
            --output-dir build \
            src/led_blink.ino

      - name: Start HTTP server in background
        run: |
          nohup python3 -m http.server --directory build 8080 &
          sleep 5

      - name: Publish OTA URL via MQTT
        run: |
          sudo apt-get install -y mosquitto-clients
          IP=$(curl -s ifconfig.me)
          URL="http://$IP:8080/led_blink.ino.bin"
          echo "Publishing OTA URL: $URL"
          mosquitto_pub -h broker.hivemq.com -t ota/update/url -m "$URL"
